import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import {DOMParser,XMLSerializer} from '@xmldom/xmldom';
import {getStored,putStored,readWorkbook,writeWorkbook,permit,type SavedWorkbook} from '../lib/local-files';
import {ensurePeriod} from '../lib/period-files';
Object.assign(globalThis,{DOMParser,XMLSerializer,window:{dispatchEvent:()=>true}});
const denied={getFileHandle:async()=>{throw new DOMException('blocked','NotAllowedError');}} as any;
assert.equal(await readWorkbook(denied,'test.xlsx'),undefined);
assert.equal((await getStored<any>('storage:choice')).mode,'browser');
assert.equal(await writeWorkbook(denied,'test.xlsx',new Uint8Array()),false);
const revoked={getFileHandle:async()=>({getFile:async()=>({arrayBuffer:async()=>new Uint8Array([1]).buffer}),createWritable:async()=>{throw new DOMException('blocked','SecurityError');}})} as any;
assert.equal(await writeWorkbook(revoked,'test.xlsx',new Uint8Array([2]),new Uint8Array([1])),false);
const quota={getFileHandle:async()=>{throw new DOMException('full','QuotaExceededError');}} as any;
await assert.rejects(readWorkbook(quota,'test.xlsx'),{name:'QuotaExceededError'});
await permit({requestPermission:async()=>{throw new DOMException('gesture','SecurityError');}} as any);
const file=await ensurePeriod('hours','2026-09-24','Testi Testiajo');
assert.equal(file.savedToFolder,false);
assert.ok((await getStored<SavedWorkbook>(`workbook:${file.filename}`))?.bytes.length);
console.log('PASS: permission fallback, write revocation, quota preserved, hours stored locally');
