import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DOMParser,XMLSerializer} from '@xmldom/xmldom';
import 'fake-indexeddb/auto';
import {openPamark,existingPamarkDay,pristineDay} from '../lib/open-pamark';
import {putStored,getStored,type SavedWorkbook} from '../lib/local-files';
import {fillWorkbook} from '../lib/workbook-export';
import {newDraft} from '../lib/capture';
import {XlsxDocument} from '../lib/xlsx-document';
Object.assign(globalThis,{DOMParser,XMLSerializer,localStorage:{getItem:()=>null},window:{dispatchEvent:()=>true}});
Object.defineProperty(navigator,'onLine',{value:false,configurable:true});
// Local-only: any network attempt is a failure, so this test also proves no shared call is made.
let requests=0;globalThis.fetch=async()=>{requests++;throw new TypeError('offline');};
const template=new Uint8Array(readFileSync('work/template-tests/pamark.xlsx'));
await putStored('template:pamark',{name:'pamark.xlsx',bytes:template});
await putStored('storage:choice',{mode:'browser'});
const filename='Pamark ajolista syyskuu 1-2 2026.xlsx';
const draft=newDraft();Object.assign(draft.values,{vehicle:'ZLC-613',date:'2026-09-02',start:'06:00',end:'15:00',startKm:'1000',endKm:'1200',loadingHours:'0.5',stops:'12',route:'Turku – Salo'});
let opened=await openPamark('2026-09-02','Testi');
assert.equal(opened.source,'local');assert.equal(opened.filename,filename);assert.match(opened.message,/Uusi ajolista/);assert.equal(requests,0);
const sections=new XlsxDocument(opened.bytes!).snapshot();
assert.equal(Object.keys(sections).filter(a=>/^E\d+$/.test(a)&&/^AUTO\s*:/i.test(String(sections[a].value))).length,6);
const empty=newDraft();empty.values.date='2026-09-02';empty.values.vehicle='ZLC-613';assert.ok(pristineDay(empty));assert.equal(existingPamarkDay(opened.bytes!,empty),undefined);
const stored=await getStored<SavedWorkbook>('workbook:'+filename);
await putStored('workbook:'+filename,{...stored!,bytes:fillWorkbook(stored!.bytes,'pamark',draft,'Testi',{fresh:false}).bytes});
opened=await openPamark('2026-09-02','Testi');
assert.equal(opened.message,'Ajolista avattu tältä laitteelta.');
const hydrated=existingPamarkDay(opened.bytes!,empty)!;assert.equal(hydrated.values.route,draft.values.route);assert.equal(hydrated.values.start,'06:00');assert.equal(hydrated.values.end,'15:00');assert.equal(hydrated.values.loadingHours,'0.5');assert.equal(hydrated.values.stops,'12');assert.ok(!pristineDay(hydrated));
assert.equal(existingPamarkDay(opened.bytes!,{...empty,values:{...empty.values,vehicle:'ABC-123'}}),undefined);
const later=await openPamark('2026-09-20','Testi');
assert.notEqual(later.filename,filename);assert.ok((await getStored<SavedWorkbook>('workbook:'+later.filename))!.bytes);
assert.equal((await getStored<SavedWorkbook>('workbook:'+filename))!.bytes.length,opened.bytes!.length);
await assert.rejects(openPamark('2099-01-01','Testi'),/tulevaisuudessa/);
await assert.rejects(openPamark('2026-13-40','Testi'),/päivämäärä/);
assert.equal(requests,0);
console.log('PASS: local-only ajolista, empty period creation with six vehicle sections, row hydration, missing vehicle ignored, separate second half-month file, future and invalid dates refused, and no network access');
