import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {DOMParser,XMLSerializer} from '@xmldom/xmldom';
import 'fake-indexeddb/auto';
import {newDraft} from '../lib/capture';
import {fillWorkbook,emptyWorkbook} from '../lib/workbook-export';
import {existingHoursDay,hoursDays} from '../lib/read-hours';
import {existingPamarkDay} from '../lib/open-pamark';
import {XlsxDocument} from '../lib/xlsx-document';
import {hoursTemplate} from '../lib/hours-template';
import {importHours} from '../lib/import-hours';
import {getStored,type SavedWorkbook} from '../lib/local-files';
Object.assign(globalThis,{DOMParser,XMLSerializer,window:{dispatchEvent:()=>true}});
const hours=new Uint8Array(readFileSync('work/template-tests/hours.xlsx'));
const pamark=new Uint8Array(readFileSync('work/listat-fixtures/Pamark ajolista syyskuu 1-2 2026.xlsx'));
const draft=newDraft();Object.assign(draft.values,{date:'2026-09-21',vehicle:'ENR-210',start:'22:00',end:'06:00',startKm:'1000',endKm:'1200',waiting:'30',breakMinutes:'45',allowance:'1',foreignAllowance:'0',sick:'0',loadingHours:'0.5',stops:'12',route:'Turku – Salo'});draft.overnight=true;
const filled=fillWorkbook(hours,'hours',draft,'Testi Testiajo',{fresh:true}).bytes;
const blank=newDraft();blank.values.date=draft.values.date;
const found=existingHoursDay(filled,blank,'Testi Testiajo')!;
for(const k of ['vehicle','date','start','end','startKm','endKm','waiting','breakMinutes','allowance','foreignAllowance','sick','route'] as const)assert.equal(found.values[k],draft.values[k],k);
assert.equal(found.overnight,true);blank.values.date='2026-09-20';assert.equal(existingHoursDay(filled,blank,'Testi Testiajo'),undefined);
assert.throws(()=>hoursDays(filled,'Toinen Kuljettaja'),/nimi/);
const sick=newDraft();Object.assign(sick.values,{date:'2026-09-22',sick:'1',allowance:'0',foreignAllowance:'0'});
const sickFile=fillWorkbook(filled,'hours',sick,'Testi Testiajo',{fresh:false}).bytes;
assert.equal(existingHoursDay(sickFile,sick,'Testi Testiajo')!.values.start,'');
assert.equal((await importHours(filled,'Testi Testiajo')).date,'2026-09-21');
assert.deepEqual((await getStored<SavedWorkbook>('workbook:Tuntilista Testi0926.xlsx'))!.bytes,filled);
const merged=await importHours(sickFile,'Testi Testiajo');
assert.deepEqual(merged.conflicts,[]);assert.equal(merged.written,1);
const afterMerge=await getStored<SavedWorkbook>('workbook:Tuntilista Testi0926.xlsx');
assert.deepEqual(hoursDays(afterMerge!.bytes,'Testi Testiajo').sort(),['2026-09-21','2026-09-22']);
assert.equal(existingHoursDay(afterMerge!.bytes,sick,'Testi Testiajo')!.values.sick,'1');
const sep21=newDraft();sep21.values.date='2026-09-21';
const changed=existingHoursDay(filled,sep21,'Testi Testiajo')!;changed.values.endKm='1500';
const changedFile=fillWorkbook(filled,'hours',changed,'Testi Testiajo',{fresh:false,overwrite:true}).bytes;
const clash=await importHours(changedFile,'Testi Testiajo');
assert.deepEqual(clash.conflicts,['2026-09-21']);assert.equal(clash.written,0);
const kept=await getStored<SavedWorkbook>('workbook:Tuntilista Testi0926.xlsx');
assert.equal(existingHoursDay(kept!.bytes,sep21,'Testi Testiajo')!.values.endKm,'1200','ristiriitainen puhelimen arvo säilyy');
assert.ok(hoursDays(kept!.bytes,'Testi Testiajo').includes('2026-09-22'),'puhelimella ollut päivä säilyy tuonnista');
const forced=await importHours(changedFile,'Testi Testiajo',true);
assert.deepEqual(forced.conflicts,[]);assert.equal(forced.written,1);
const done=await getStored<SavedWorkbook>('workbook:Tuntilista Testi0926.xlsx');
assert.equal(existingHoursDay(done!.bytes,sep21,'Testi Testiajo')!.values.endKm,'1500');
assert.ok(hoursDays(done!.bytes,'Testi Testiajo').includes('2026-09-22'),'vahvistettu korvaus ei pudota puhelimen päivää');
const snap=new XlsxDocument(sickFile).snapshot();
const free=hoursTemplate.entryRows.find(r=>snap[`A${r}`]?.value==null||snap[`A${r}`]?.value==='')!;
const half=new XlsxDocument(sickFile);half.set(`A${free}`,(Date.parse('2026-09-23T00:00:00Z')-Date.UTC(1899,11,30))/86400000);
const halfFile=half.bytes();
assert.ok(hoursDays(halfFile,'Testi Testiajo').includes('2026-09-23'),'puolitäytetty päivä lasketaan päiväksi');
const partial=await importHours(halfFile,'Testi Testiajo');
const broken=partial.failed.find(f=>f.date==='2026-09-23');
assert.ok(broken,'puolitäytetty päivä raportoidaan');
assert.match(broken!.reason,/Täytä/,`syy kerrotaan, ei vain päivämäärää: ${broken!.reason}`);
const p=fillWorkbook(pamark,'pamark',draft,'Testi Testiajo',{fresh:true}).bytes;
assert.equal(existingPamarkDay(p,draft)!.values.route,draft.values.route);
console.log('PASS: hours roundtrip, dates, vehicle/route, overnight, durations, allowances, sickness, byte-preserving first import, day-wise merge keeping phone-only days, reported clash without overwrite and confirmed overwrite, half-filled day reported with its reason; Pamark day reading');

if(process.env.AJOLISTA_UI_FIXTURE==='1')writeFileSync('work/template-tests/ui-hours.xlsx',filled);
