import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DOMParser,XMLSerializer} from '@xmldom/xmldom';
import 'fake-indexeddb/auto';
import {newDraft} from '../lib/capture';
import {existingPamarkDay} from '../lib/open-pamark';
import {enqueuePamark,flushPamark,syncJobs} from '../lib/pamark-sync';
import {connectGoogle,setDriveFolder,XLSX_MIME} from '../lib/google-drive';
import {putStored} from '../lib/local-files';
import {XlsxDocument} from '../lib/xlsx-document';
Object.assign(globalThis,{DOMParser,XMLSerializer,localStorage:{getItem:()=>null},window:{dispatchEvent:()=>true,google:{accounts:{oauth2:{initTokenClient:(c:any)=>({requestAccessToken:()=>c.callback({access_token:'test',expires_in:3600})})}}}}});
const original=new Uint8Array(readFileSync('work/listat-fixtures/Pamark ajolista syyskuu 1-2 2026.xlsx'));let remote=original,version=1,writes=0,race=true;
await putStored('template:pamark',{name:'copy.xlsx',bytes:original});await connectGoogle();await setDriveFolder({id:'test-only-folder',name:'test'});
const metadata=()=>({id:'copy',mimeType:XLSX_MIME,etag:String(version),version:String(version)});
globalThis.fetch=async(input,options)=>{const u=new URL(String(input));if(u.pathname==='/drive/v2/files')return Response.json({items:[metadata()]});if(u.pathname==='/drive/v2/files/copy'){if(u.searchParams.get('alt')!=='media')return Response.json(metadata());assert.equal(new Headers(options?.headers).get('If-Match'),null);return new Response(remote);}if(u.pathname==='/upload/drive/v2/files/copy'){assert.equal(new Headers(options?.headers).get('If-Match'),String(version));if(race){race=false;const d=new XlsxDocument(remote);d.set('K36',88);remote=d.bytes();version++;return new Response('',{status:412});}remote=new Uint8Array(options!.body as Uint8Array);version++;writes++;return Response.json(metadata());}throw Error(u.pathname);};
const base=newDraft();Object.assign(base.values,{date:'2026-09-01',vehicle:'JTS-790'});const edit=existingPamarkDay(original,base)!;edit.values.route='Korjaus yksi';await enqueuePamark(edit,'Testi');await flushPamark();assert.equal(existingPamarkDay(remote,base)!.values.route,'Korjaus yksi');assert.equal(new XlsxDocument(remote).snapshot().K36.value,88);assert.equal(writes,1);
edit.values.route='Korjaus kaksi';await enqueuePamark(edit,'Testi');await flushPamark();assert.equal(existingPamarkDay(remote,base)!.values.route,'Korjaus kaksi');assert.equal(writes,2);
edit.values.route='Oma kolmas';await enqueuePamark(edit,'Testi');const changed=new XlsxDocument(remote);changed.set('K4',77);remote=changed.bytes();await assert.rejects(flushPamark(),/erilainen/);assert.equal(writes,2);assert.equal((await syncJobs())[edit.id].status,'error');assert.equal(new XlsxDocument(remote).snapshot().K4.value,77);
console.log('PASS simulated Drive with real source copy: original-row correction, ETag retry preserving another driver, repeated own edit after sync, concurrent same-row rejection without upload');
